name: "build app"
run-name: "${{ github.actor }} is running build scripts"

on: [pull_request]

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
      - run: npm ci
      - run: npm run build
