name: Deployment

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  install:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Installing packages
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
      - run: npm ci
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: Building
      - run: npm run build
  configurate:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - run: cp ../.env .
      - run: npx prisma migrate dev
